import time
print()
print("|========|")
time.sleep(0.1)
print("|AdubamOS|   AdubamOS pre2 1.0")
time.sleep(0.1)
print("|( 0)(0 )|   Adu-Shell v1.0b")
time.sleep(0.1)
print("|   --   |   r - release")
time.sleep(0.1)
print("|========|   b - beta")
print()
